name: Update formula on release

on:
  repository_dispatch:
    types: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate sha256
        id: sha
        env:
          TAG: ${{ github.event.client_payload.tag }}
        run: |
          SHA256=`curl -fLs https://github.com/XCTestHTMLReport/XCTestHTMLReport/archive/refs/tags/${TAG}.tar.gz |\
          sha256sum |\
          awk '{print $1}'`
          echo ::set-output name=sha256::${SHA256}

      - name: Template substitution
        env:
          TAG: ${{ github.event.client_payload.tag }}
          SHA256: ${{ steps.sha.outputs.sha256 }}
        run: |
          sed -e "s:{{ TAG }}:$TAG:g" -e "s:{{ SHA256 }}:$SHA256:g" xchtmlreport.rb.tmpl > Formula/xchtmlreport.rb
          cp Formula/xchtmlreport.rb Formula/xchtmlreport@$TAG.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          TAG: ${{ github.event.client_payload.tag }}
        with:
          title: "${{ env.TAG }} Formula Version Bump"
          body: "Bumping version from upstream release\nhttps://github.com/XCTestHTMLReport/XCTestHTMLReport/releases/tag/${{ env.TAG }}"
          commit-message: "${{ env.TAG }} formula version bump"
          branch: "formula-bump/${{ env.TAG }}"
          add-paths: xchtmlreport.rb
          reviewers: tylervick
